name: 'insurance_semantic_layer'
version: '1.0.0'
config-version: 2

profile: 'insurance_semantic_layer'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  insurance_semantic_layer:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

seeds:
  insurance_semantic_layer:
    +schema: raw
